baseURL = "http://example.org/"
languageCode = "en-us"
title = "Andreas Olsson"
theme = "jawee-hugo-theme"

## Site Settings
[params]
author = "Andreas Olsson"
intro = "Software Developer"
description = "Senior Specialist at Netcompany, DK"
dateformat = "Jan 2, 2006"

## Social Accounts
[params.social]
github = "jawee"
instagram = "jawee15"
linkedin = "andreas-olsson-86597559"
twitter = "andreasnolsson"
facebook = "andreas.olsson.961"

youtube = "UCD0rORXiklcWPcLR6xO52NQ"
twitch = "jawee15"
email = "olsson.andreas@gmail.com"

## Extras
[params.extra]
copyright = "© 2020. Andreas Olsson."
poweredby = true
highlightjs = true
socialmarkup = true
toc = true
displayrssicon = false